create table HUMAN (
  ID int not null generated by default as identity,
  LOGIN varchar(255) not null,
  PASSWORD varchar(255) not null,
  unique (ID),
  unique (LOGIN),
  primary key (ID)
);
create index HUMAN_INDEX_0 on HUMAN(LOGIN);
create table RECORD (
  ID int not null generated by default as identity,
  HUMANID int not null,
  LEADERBOARDID int not null,
  LEVEL int not null,
  ACHEVEDAT timestamp,
  unique (ID),
  primary key (ID)
);
create index RECORD_INDEX_0 on RECORD(HUMANID);
create index RECORD_INDEX_1 on RECORD(LEADERBOARDID);
create table LEADERBOARD (
  ID int not null generated by default as identity,
  TITLE varchar(255) not null,
  DESCRIPTION varchar(255),
  ISACTIVE boolean not null,
  unique (ID),
  primary key (ID)
);
create index LEADERBOARD_INDEX_0 on LEADERBOARD(TITLE);
create table LIKES (
  ID int not null generated by default as identity,
  HUMANID int not null,
  RECORDID int not null,
  ISPOSITIVE boolean not null,
  unique (ID),
  primary key (ID)
);
create index LIKES_INDEX_0 on LIKES(RECORDID);
alter table RECORD add foreign key (HUMANID) references HUMAN (ID) on delete no action on update no action;
alter table RECORD add foreign key (LEADERBOARDID) references LEADERBOARD (ID) on delete no action on update no action;
alter table LIKES add foreign key (HUMANID) references HUMAN (ID) on delete no action on update no action;
alter table LIKES add foreign key (RECORDID) references RECORD (ID) on delete no action on update no action;